"""
understand_variables.py
=======================
Explains every variable across all 4 datasets in this study.
No plots — just clear printed output showing what each column means,
its values, and how it maps to your research questions.

Usage (with your full data folders):
    python understand_variables.py \
        --multi_lab   "data/multiple/lab/*.csv" \
        --multi_phone "data/multiple/phone/*.csv" \
        --single_lab  "data/single/lab/*.csv" \
        --single_phone "data/single/phone/*.csv"

Or run with the 4 sample files (default, no args needed).
"""

import argparse, ast, glob, os, textwrap
import numpy as np
import pandas as pd

# ── colour helpers (terminal) ─────────────────────────────────────────────────
BOLD   = "\033[1m"
CYAN   = "\033[96m"
YELLOW = "\033[93m"
GREEN  = "\033[92m"
RESET  = "\033[0m"
DIM    = "\033[2m"

def header(title):
    print(f"\n{BOLD}{CYAN}{'═'*70}{RESET}")
    print(f"{BOLD}{CYAN}  {title}{RESET}")
    print(f"{BOLD}{CYAN}{'═'*70}{RESET}")

def section(title):
    print(f"\n{BOLD}{YELLOW}  ── {title} ──{RESET}")

def var(name, dtype, meaning, values_note, relevance):
    print(f"\n  {BOLD}{GREEN}{name}{RESET}  {DIM}[{dtype}]{RESET}")
    print(f"    What it is : {meaning}")
    print(f"    Values     : {values_note}")
    print(f"    Relevance  : {relevance}")

def note(msg):
    print(f"\n  {DIM}ℹ  {msg}{RESET}")

# ── parse helpers ─────────────────────────────────────────────────────────────

def safe_list(val):
    try:
        r = ast.literal_eval(str(val))
        return list(r) if isinstance(r, (list, tuple)) else [r]
    except Exception:
        return []

# ── loaders ───────────────────────────────────────────────────────────────────

def load_one_lab(fp):
    raw = pd.read_csv(fp, dtype=str)
    return raw, raw[raw["target_col"].isin(["white", "red"])].copy()

def load_one_phone(fp):
    return pd.read_csv(fp)

# ─────────────────────────────────────────────────────────────────────────────
# 1.  LAB FILES  (both Single and Multiple use same PsychoPy format)
# ─────────────────────────────────────────────────────────────────────────────

def explain_lab(fp_multi, fp_single):
    header("LAB FILES  —  PsychoPy visual_search_*.csv")
    raw_m, tr_m = load_one_lab(fp_multi)
    raw_s, tr_s = load_one_lab(fp_single)

    print(f"""
  These files are generated by PsychoPy (a psychology experiment software).
  Each file = one participant's entire session.
  Each row = one trial (one stimulus display where the participant had to click).

  Multiple-target file: {os.path.basename(fp_multi)}  →  {len(tr_m)} trial rows
  Single-target file : {os.path.basename(fp_single)}  →  {len(tr_s)} trial rows

  NOTE: The first 2 rows in each file are bookkeeping rows (instructions screen
  data). Only rows where target_col == 'white' or 'red' are actual trials.
""")

    section("A) TRIAL IDENTITY COLUMNS")

    var("target_col",
        "string",
        "The colour of the BACKGROUND of the search display for that trial. "
        "This encodes whether the trial contains a target.",
        "'white' = distractor-only (no target, lure trial) | 'red' = target present",
        "DV split: use red rows for Hit Rate; use white rows for False Alarm Rate. "
        "In Single condition 'red' = 1 target; in Multiple condition 'red' = 5 targets on white BG.")

    var("trials.thisRepN",
        "int",
        "Which repetition of the full trial list this trial belongs to (PsychoPy loop counter).",
        "Starts at 0. Usually 0 for a single-pass design.",
        "Mostly bookkeeping. Useful if you want to check whether trial order effects exist.")

    var("trials.thisTrialN",
        "int",
        "Trial number within the current repetition (0-indexed).",
        "0, 1, 2 … up to N_trials-1",
        "Use for order / fatigue analysis (RQ4 analogue in lab data).")

    var("trials.thisN",
        "int",
        "Absolute trial number across the whole session (0-indexed).",
        "0, 1, 2 … 14 (for 15 trials)",
        "Same as above but global. Useful if multiple repetitions exist.")

    var("trials.thisIndex",
        "int",
        "Index into the conditions file (the row in the stimulus list that was selected).",
        "Integer index",
        "Lets you look up the original stimulus parameters if you have the conditions CSV.")

    var("thisRow.t",
        "float (seconds)",
        "Absolute time (from experiment start) at which this trial's row was prepared by PsychoPy.",
        "Cumulative seconds e.g. 6.99, 15.74 …",
        "Not a DV. Useful only for debugging timing issues.")

    section("B) INSTRUCTIONS SCREEN COLUMNS  (only populated in the first 2 rows)")

    var("instructions.started / .stopped",
        "float (seconds)",
        "Onset and offset time of the instruction screen.",
        "Only non-NaN in the first blank row",
        "Not used in analysis. Tells you how long participant read instructions.")

    var("instrTxt.started / startMouse.started",
        "float (seconds)",
        "When the instruction text component and start-mouse became active.",
        "Same as above",
        "Bookkeeping only.")

    var("startMouse.x / .y / .leftButton / .midButton / .rightButton",
        "float / int",
        "Mouse position and button state at the moment the participant clicked 'start' to begin.",
        "x, y in normalised units (−1 to 1); button states 0/1",
        "Not a DV. Could indicate attentiveness at task start if needed.")

    section("C) TRIAL TIMING COLUMNS  ← KEY for RT")

    var("trial.started",
        "float (seconds)",
        "Absolute time (from experiment start) when the stimulus display appeared on screen.",
        "e.g. 6.87, 15.64, 23.06 … (cumulative across session)",
        "Used as denominator to compute RT. RT = click_time_relative + (trial.started offset) "
        "OR just use mouse.time / click_times directly (they are already relative to trial onset).")

    var("trial.stopped",
        "float (seconds)",
        "Absolute time when the trial ended (last click recorded / timeout).",
        "e.g. 14.63, 22.05, 28.51 …",
        "trial.stopped − trial.started = total trial duration. "
        "For Multiple condition this ≈ time to find and click ALL 5 targets.")

    # Compute and show example trial durations
    tr_m["dur"] = tr_m["trial.stopped"].astype(float) - tr_m["trial.started"].astype(float)
    tr_s["dur"] = tr_s["trial.stopped"].astype(float) - tr_s["trial.started"].astype(float)
    print(f"\n    Example trial durations (Multiple / Lab): "
          f"M={tr_m['dur'].mean()*1000:.0f}ms, SD={tr_m['dur'].std()*1000:.0f}ms")
    print(f"    Example trial durations (Single  / Lab): "
          f"M={tr_s['dur'].mean()*1000:.0f}ms, SD={tr_s['dur'].std()*1000:.0f}ms")

    var("square.started",
        "float (seconds)",
        "When the square stimulus (target box / grid) appeared.",
        "Very close to trial.started",
        "Can verify stimulus onset jitter — usually ignore.")

    var("mouse.started",
        "float (seconds)",
        "When the mouse component was activated to start recording clicks.",
        "Very close to trial.started",
        "Bookkeeping.")

    var("trial_counter.started / instruct.started",
        "float (seconds)",
        "When the trial counter text and on-screen instruction text appeared.",
        "Close to trial.started",
        "Bookkeeping.")

    var("target.started",
        "float (seconds)",
        "⚠ SINGLE-TARGET ONLY — when the actual target stimulus appeared.",
        "Non-NaN only in Single lab files",
        "In Single condition the target appears AFTER a brief delay. "
        "True RT = mouse.time[0] − (target.started − trial.started). "
        "This column does NOT exist in Multiple lab files because all targets appear simultaneously.")

    section("D) RESPONSE COLUMNS  ← KEY DVs")

    var("click_times   [MULTIPLE LAB ONLY]",
        "list of floats (seconds, relative to trial onset)",
        "Time of each mouse click within the trial, measured from trial.started. "
        "One value per target clicked.",
        f"e.g. {tr_m['click_times'].iloc[0]}\n"
        "       → 5 values because there are 5 targets per trial.",
        "PRIMARY RT SOURCE for Multiple/Lab.\n"
        "       • click_times[0] = Initial Response Time (RT to first target) ← main DV\n"
        "       • click_times[i] − click_times[i−1] = Inter-Target Time\n"
        "       • len(click_times) = how many targets were clicked (max=5)")

    note("click_times does NOT exist in Single lab files. Single uses mouse.time instead.")

    val_mt = tr_s["mouse.time"].iloc[0]
    var("mouse.time   [SINGLE LAB — and also present in Multiple as a copy of click_times]",
        "list of floats (seconds, relative to trial onset)",
        "For Single: list with exactly 1 element — the time taken to click the single target.\n"
        "  For Multiple: same as click_times (redundant copy).",
        f"Single example: {val_mt}  → one click\n"
        f"  Multiple example: {tr_m['mouse.time'].iloc[0]}",
        "PRIMARY RT SOURCE for Single/Lab.\n"
        "       RT (ms) = mouse.time[0] × 1000")

    var("mouse.clicked_name",
        "list of strings",
        "Name(s) of the PsychoPy component(s) that were clicked during the trial.",
        "Single: ['target'] if correct, [] if missed, ['distractor_X'] if false alarm\n"
        "  Multiple: ['target_0','target_4','target_1','target_3','target_2'] — order reflects click sequence",
        "ACCURACY DV.\n"
        "       Single  → hit = 'target' in list; false_alarm = non-target name in list\n"
        "       Multiple → n_hits = count of 'target_X' names; n_expected = 5\n"
        "                  accuracy = n_hits / 5")

    section("E) MOUSE TRAJECTORY COLUMNS  (fine-grained, usually not used for main DVs)")

    var("mouse.x / mouse.y",
        "list of floats (normalised screen coords −1 to 1)",
        "X and Y position of the mouse at each recorded click event.",
        "One entry per click, same length as click_times / mouse.time",
        "Can be used for spatial analysis — e.g. were misses clustered in one region?")

    var("mouse.leftButton / .midButton / .rightButton",
        "list of ints (0 or 1)",
        "Button state at each recorded time point (1=pressed, 0=not pressed).",
        "Mostly [1,1,1,…] for left button (all valid clicks)",
        "Can sanity-check that only left-clicks were recorded.")

    section("F) FEEDBACK SCREEN COLUMNS  (post-trial, not DVs)")

    var("feedback.started / fb.started / trial_counter_2.started",
        "float (seconds)",
        "Onset of the post-trial feedback screen and its components.",
        "Cumulative seconds",
        "Not DVs. The gap feedback.started − trial.stopped = feedback latency.")

    var("feedback.stopped / fb.stopped / trial_counter_2.stopped",
        "float (seconds)",
        "Offset of the feedback screen.",
        "Multiple lab only (Single has these as NaN in some rows)",
        "Not DVs.")

    var("thanks.started / endMsg.started / thanks.stopped",
        "float (seconds)",
        "Onset/offset of the end-of-task 'thank you' screen.",
        "Only non-NaN in the very last row of the file",
        "Not DVs.")

    section("G) SESSION METADATA COLUMNS")

    var("participant",
        "string",
        "Participant identifier entered at experiment launch.",
        f"e.g. '{tr_m['participant'].iloc[0]}' (Multiple) | '{tr_s['participant'].iloc[0]}' (Single)",
        "Used to join lab and phone data for the same participant. "
        "Map to PlayerID in phone files (e.g. participant '22' ↔ PlayerID 'Player_22').")

    var("session",
        "float",
        "Session number (entered at launch, usually 1 or 2 for counterbalancing).",
        f"e.g. {tr_m['session'].iloc[0]}",
        "Track counterbalancing — whether participant did Game first or Lab first.")

    var("date",
        "string",
        "Date/time string of when the experiment was run.",
        "Format: YYYY-MM-DD_HHhMM.SS.mmm",
        "Can compute time-on-task or check for outlier sessions.")

    var("expName / psychopyVersion / frameRate / expStart",
        "strings / float",
        "Name of the experiment script, PsychoPy version used, monitor refresh rate, and ISO start time.",
        "e.g. 'visual_search', '2024.1.5', None (frameRate not logged), '2026-02-06 13h34…'",
        "Bookkeeping / reproducibility. frameRate=None means it wasn't recorded — not a concern.")


# ─────────────────────────────────────────────────────────────────────────────
# 2.  PHONE / GAME FILES  (Single & Multiple — same 12 columns)
# ─────────────────────────────────────────────────────────────────────────────

def explain_phone(fp_multi, fp_single):
    header("PHONE / GAME FILES  —  attentional_spotter_results.csv")
    df_m = load_one_phone(fp_multi)
    df_s = load_one_phone(fp_single)

    print(f"""
  These files come from the mobile "Attentional Spotter" game app.
  Each file = one participant's full game session.
  Each row = one completed (or failed) LEVEL attempt.

  Multiple-target file: {os.path.basename(fp_multi)}  →  {len(df_m)} level rows, levels {df_m['Level'].min()}–{df_m['Level'].max()}
  Single-target file : {os.path.basename(fp_single)}  →  {len(df_s)} level rows, levels {df_s['Level'].min()}–{df_s['Level'].max()}

  Key structural difference from lab files:
    Lab    → unit of analysis = TRIAL  (one stimulus, one response)
    Phone  → unit of analysis = LEVEL  (one level = multiple targets hidden in a scene)
""")

    section("A) PARTICIPANT & SESSION IDENTITY")

    var("PlayerID",
        "string",
        "Game-assigned player identifier.",
        f"e.g. '{df_m['PlayerID'].iloc[0]}'  (numeric suffix maps to participant number)",
        "Use to join with lab files: PlayerID 'Player_22' ↔ participant '22' in lab CSV.")

    var("Timestamp",
        "ISO datetime string",
        "Date and time when this level was completed.",
        f"e.g. '{df_m['Timestamp'].iloc[0]}'",
        "Can compute inter-level pause times or session duration. "
        "Also lets you verify lab and game were done on the same day.")

    var("GameMode",
        "string (categorical)",
        "Which version of the game was played.",
        "'singleTarget' (Single condition) | 'multipleTargets' (Multiple condition)",
        "The BETWEEN-subjects IV. Confirms which group this participant belongs to.")

    section("B) LEVEL STRUCTURE  ← KEY for RQ4")

    var("Level",
        "int",
        "The level number attempted. Levels increase in difficulty.",
        f"Single: 1–{df_s['Level'].max()} | Multiple: 1–{df_m['Level'].max()}\n"
        "  Difficulty increases = more distractors, more targets, shorter time",
        "IV for RQ4 (effect of level on performance). "
        "⚠ A participant can RETRY a failed level — so the same Level number can appear "
        "multiple times for one participant (see Completed column).")

    # Show level repeats
    level_counts_m = df_m['Level'].value_counts().sort_index()
    print(f"\n    Multiple: level attempt counts:\n{level_counts_m.to_string()}")
    print(f"\n    Single: all levels completed once (Completed all True)")

    section("C) PERFORMANCE DVs  ← MAIN GAME OUTCOMES")

    var("FinalScore",
        "int",
        "Cumulative game score at the end of this level.",
        f"Single: {df_s['FinalScore'].min()}–{df_s['FinalScore'].max()} (increments of 10)\n"
        "  Multiple: varies (more targets per level = larger increments)",
        "Composite performance metric. Useful for overall learning curve / RQ4. "
        "Note: if a level is retried, score may RESET or carry forward — check carefully.")

    var("Completed",
        "bool",
        "Whether the participant successfully completed (passed) this level attempt.",
        f"True / False\n"
        f"  Multiple — False attempts: {(df_m['Completed']==False).sum()} out of {len(df_m)}\n"
        f"  Single   — False attempts: {(df_s['Completed']==False).sum()} out of {len(df_s)}",
        "Important filter: for most analyses use only Completed==True rows. "
        "False rows represent failed attempts with partial data.")

    var("SuccessRate(%)",
        "float  0–100",
        "Percentage of TARGETS correctly identified within this level "
        "(hits / total targets × 100), PENALISED for false alarms.\n"
        "  Formula: SuccessRate = (HitRate − FalseAlarmPenalty) capped at 0.",
        f"Multiple range: {df_m['SuccessRate(%)'].min():.1f}–{df_m['SuccessRate(%)'].max():.1f}%\n"
        f"  Single range : {df_s['SuccessRate(%)'].min():.1f}–{df_s['SuccessRate(%)'].max():.1f}%",
        "PRIMARY ACCURACY DV for phone data (preferred over HitRate alone "
        "because it penalises false alarms).")

    var("HitRate(%)",
        "float  0–100",
        "Raw percentage of targets correctly tapped, WITHOUT false alarm penalty.\n"
        "  = (number of correct taps / number of targets) × 100",
        f"Multiple range: {df_m['HitRate(%)'].min():.1f}–{df_m['HitRate(%)'].max():.1f}%\n"
        f"  Single range : {df_s['HitRate(%)'].min():.1f}–{df_s['HitRate(%)'].max():.1f}%",
        "Use when you want pure sensitivity (d') without criterion effects. "
        "For single-target: 100% = hit, 0% = miss.")

    var("FalseAlarms",
        "int  ≥ 0",
        "Count of incorrect taps on NON-target items during this level.",
        f"Multiple: 0–{df_m['FalseAlarms'].max()} | Single: 0–{df_s['FalseAlarms'].max()}",
        "SPECIFICITY / criterion DV. "
        "Higher = impulsive responding. Compare across conditions for speed-accuracy trade-off.")

    section("D) REACTION TIME DVs")

    var("InitialResponseTime(ms)",
        "int  (milliseconds)",
        "Time from the level START (stimulus display appears) to the FIRST tap.",
        f"Multiple: M={df_m['InitialResponseTime(ms)'].mean():.0f}ms, "
        f"SD={df_m['InitialResponseTime(ms)'].std():.0f}ms, "
        f"range {df_m['InitialResponseTime(ms)'].min()}–{df_m['InitialResponseTime(ms)'].max()}ms\n"
        f"  Single:   M={df_s['InitialResponseTime(ms)'].mean():.0f}ms, "
        f"SD={df_s['InitialResponseTime(ms)'].std():.0f}ms, "
        f"range {df_s['InitialResponseTime(ms)'].min()}–{df_s['InitialResponseTime(ms)'].max()}ms",
        "PRIMARY RT DV for phone data. Analogous to mouse.time[0] in lab files. "
        "Use this for RQ1 (validity) and RQ3 (modality comparison).")

    var("AvgInterTargetTime(ms)",
        "int  (milliseconds)",
        "Average time BETWEEN successive target taps within a level.\n"
        "  = mean of (tap[i] − tap[i−1]) for i > 0\n"
        "  For single-target this is always 0 (only one tap, no interval possible).",
        f"Multiple: M={df_m['AvgInterTargetTime(ms)'].mean():.0f}ms, "
        f"range {df_m['AvgInterTargetTime(ms)'].min()}–{df_m['AvgInterTargetTime(ms)'].max()}ms\n"
        f"  Single: always 0",
        "MULTIPLE CONDITION ONLY meaningful DV. Captures search efficiency / visual scanning speed. "
        "Analogous to inter-click times derived from click_times in multiple lab files.")

    section("E) SPATIAL DV")

    eg_m = df_m['HitPositions(x,y)'].iloc[0]
    eg_s = df_s['HitPositions(x,y)'].iloc[0]
    var("HitPositions(x,y)",
        "string — semicolon-separated (x,y) coordinate pairs",
        "Screen coordinates (pixels) where each successful tap landed.",
        f"Multiple example (level 1): {eg_m[:80]}…\n"
        f"  Single example (level 1) : {eg_s}",
        "Advanced / optional analysis only:\n"
        "       • Spatial search strategy (systematic vs random)\n"
        "       • Distance between consecutive hits → scanning path length\n"
        "       • Cluster analysis of false alarm locations\n"
        "       Parse with: [tuple(map(float,p.split(','))) for p in val.split(';')]")


# ─────────────────────────────────────────────────────────────────────────────
# 3.  CROSS-FILE ALIGNMENT  (how the 4 files connect)
# ─────────────────────────────────────────────────────────────────────────────

def explain_alignment():
    header("HOW THE 4 FILES CONNECT  —  Tidy Data & Key Mappings")

    print(f"""
  ┌─────────────────────┬────────────────────────────────────────────────────┐
  │  Condition/Modality │  File pattern                                      │
  ├─────────────────────┼────────────────────────────────────────────────────┤
  │  Single / Lab       │  <N>_visual_search_*.csv          (N = participant) │
  │  Single / Phone     │  <N>_attentional_spotter_results.csv               │
  │  Multiple / Lab     │  <N>_visual_search_*.csv          (N = participant) │
  │  Multiple / Phone   │  <N>_attentional_spotter_results.csv               │
  └─────────────────────┴────────────────────────────────────────────────────┘

  Participant linking:
    Lab  participant col  →  e.g. "sahithi", "1", "22"
    Phone PlayerID col   →  e.g. "Player_2", "Player_22"
    ⚠ You need a lookup table to match these reliably across all 37 participants.
""")

    section("DV ALIGNMENT TABLE  —  same concept, different column name per file")

    print(f"""
  Concept               │ Single/Lab           │ Multiple/Lab          │ Phone (both)
  ──────────────────────┼──────────────────────┼───────────────────────┼──────────────────────────
  Initial RT (ms)       │ mouse.time[0] × 1000 │ click_times[0] × 1000 │ InitialResponseTime(ms)
  Inter-response time   │  N/A (1 target)      │ diff(click_times)×1000│ AvgInterTargetTime(ms)
  Hit (accuracy)        │ 'target' in          │ len(clicked) / 5      │ HitRate(%) / 100
                        │  mouse.clicked_name  │                       │
  False alarm           │ non-target name in   │ N/A per trial         │ FalseAlarms (count)
                        │  mouse.clicked_name  │                       │
  Success (penalised)   │  compute manually    │  compute manually     │ SuccessRate(%)
  Trial/level #         │ trials.thisN         │ trials.thisN          │ Level
  Trial duration        │ trial.stopped −      │ trial.stopped −       │  not directly stored
                        │  trial.started       │  trial.started        │  (use timestamps)
  Participant ID        │ participant col       │ participant col       │ PlayerID col
""")

    section("BETWEEN-SUBJECTS IV  (Target Load)")
    print("""
  Participants 1–21  →  SINGLE TARGET group
      Lab file:  1_visual_search_*.csv   |  Phone file: 1_attentional_spotter_results.csv
      Each trial / level has exactly 1 target hidden among distractors.

  Participants 22–37  →  MULTIPLE TARGET group  (16 participants per brief)
      Lab file:  22_visual_search_*.csv  |  Phone file: 22_attentional_spotter_results.csv
      Each trial / level has 5 targets (lab) or growing N targets (phone game).
""")

    section("WITHIN-SUBJECTS IV  (Modality)")
    print("""
  Every participant did BOTH:
    • Lab task  (PsychoPy on a computer, controlled environment)
    • Phone game (mobile app, gamified interface)

  Counterbalancing: half did Lab first, half did Game first
    → tracked via the 'session' column in lab files (session 1 vs 2).
""")

    section("KEY ANALYTICAL NOTE — Unit of Analysis mismatch")
    print("""
  Lab  → 15 TRIALS per participant
  Phone → 15–20 LEVELS per participant (and levels can be retried)

  Before running ANOVA / t-tests you must AGGREGATE to one score per participant:
    Lab:   mean(RT_ms)  and  mean(hit) across all trials
    Phone: mean(InitialResponseTime(ms)) across completed levels

  Then you have one row per participant per modality (the standard mixed ANOVA format).
""")


# ─────────────────────────────────────────────────────────────────────────────
# 4.  QUICK DATA QUALITY SUMMARY
# ─────────────────────────────────────────────────────────────────────────────

def data_quality(fp_multi_lab, fp_multi_phone, fp_single_lab, fp_single_phone):
    header("DATA QUALITY SNAPSHOT  (sample files only)")

    print("\n  This section shows actual values from your sample files.\n"
          "  Run with full glob patterns to get stats across all participants.\n")

    dfs = {
        "Multiple / Lab  ": load_one_lab(fp_multi_lab)[1],
        "Multiple / Phone": load_one_phone(fp_multi_phone),
        "Single  / Lab  ": load_one_lab(fp_single_lab)[1],
        "Single  / Phone": load_one_phone(fp_single_phone),
    }

    for label, df in dfs.items():
        print(f"  {BOLD}{label}{RESET}")

        if "click_times" in df.columns or "mouse.time" in df.columns:
            # Lab file
            rt_col = "click_times" if "click_times" in df.columns else "mouse.time"
            rts = [safe_list(v)[0] * 1000 for v in df[rt_col] if safe_list(v)]
            if rts:
                print(f"    RT (ms):    M={np.mean(rts):.1f}  SD={np.std(rts):.1f}  "
                      f"min={np.min(rts):.1f}  max={np.max(rts):.1f}")
            hit_col = "mouse.clicked_name"
            if hit_col in df.columns and "target_col" in df.columns:
                red_rows = df[df["target_col"] == "red"]
                hits = sum("target" in str(v) for v in red_rows[hit_col])
                print(f"    Hits:       {hits}/{len(red_rows)} target-present trials")
                white_rows = df[df["target_col"] == "white"]
                fas = sum(safe_list(v) != [] and "target" not in str(v)
                          for v in white_rows[hit_col])
                print(f"    False alarms on distractor trials: {fas}/{len(white_rows)}")
            dur = df["trial.stopped"].astype(float) - df["trial.started"].astype(float)
            print(f"    Trial dur:  M={dur.mean()*1000:.0f}ms  SD={dur.std()*1000:.0f}ms")
        else:
            # Phone file
            completed = df[df["Completed"] == True]
            print(f"    Levels:     {len(df)} attempts, {len(completed)} completed "
                  f"({100*len(completed)/len(df):.0f}%)")
            print(f"    RT (ms):    M={completed['InitialResponseTime(ms)'].mean():.1f}  "
                  f"SD={completed['InitialResponseTime(ms)'].std():.1f}  "
                  f"min={completed['InitialResponseTime(ms)'].min()}  "
                  f"max={completed['InitialResponseTime(ms)'].max()}")
            print(f"    HitRate:    M={completed['HitRate(%)'].mean():.1f}%  "
                  f"SuccessRate M={completed['SuccessRate(%)'].mean():.1f}%")
            print(f"    FalseAlarms total: {completed['FalseAlarms'].sum()}")
        print()


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    default_multi_lab   = "data/multiple/lab/22_visual_search_2026-02-06_13h34.07.839.csv"
    default_multi_phone = "data/multiple/phone/22_attentional_spotter_results.csv"
    default_single_lab  = "data/single/lab/1_visual_search_2026-02-03_15h36.25.316.csv"
    default_single_phone= "data/single/phone/1_attentional_spotter_results.csv"

    parser = argparse.ArgumentParser(description="Explain variables in all 4 datasets")
    parser.add_argument("--multi_lab",    default=default_multi_lab)
    parser.add_argument("--multi_phone",  default=default_multi_phone)
    parser.add_argument("--single_lab",   default=default_single_lab)
    parser.add_argument("--single_phone", default=default_single_phone)
    args = parser.parse_args()

    # When glob patterns are passed, just pick the first file for explanation
    def resolve(pattern):
        if "*" in pattern:
            files = sorted(glob.glob(pattern))
            return files[0] if files else pattern
        return pattern

    explain_lab(resolve(args.multi_lab), resolve(args.single_lab))
    explain_phone(resolve(args.multi_phone), resolve(args.single_phone))
    explain_alignment()
    data_quality(resolve(args.multi_lab), resolve(args.multi_phone),
                 resolve(args.single_lab), resolve(args.single_phone))

    print(f"\n{BOLD}{CYAN}{'═'*70}{RESET}")
    print(f"{BOLD}  Done. All variables explained.{RESET}")
    print(f"{CYAN}{'═'*70}{RESET}\n")


if __name__ == "__main__":
    main()